// <auto-generated />
namespace OGS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class catcreation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(catcreation));
        
        string IMigrationMetadata.Id
        {
            get { return "201508301106198_catcreation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
