// <auto-generated />
namespace OGS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class allowednullaformodified : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(allowednullaformodified));
        
        string IMigrationMetadata.Id
        {
            get { return "201508301339366_allowednullaformodified"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
